[build.environment]
   YARN_VERSION = "3.2.3"
   YARN_CACHE_FOLDER = "/opt/buildhome/.yarn_cache"

[[plugins]]
package = "@netlify/plugin-lighthouse"
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    pwa = 0.0 # Skip PWA threshold for now

  [plugins.inputs]
    output_path = "lighthouse/index.html"
