[build]
  publish = "dist"

[[plugins]]
package = "netlify-plugin-html-validate"
  [plugins.inputs]
    ext = "html"
    config = ".htmlvalidate.json"
    path = "dist"

[[plugins]]
package = "netlify-plugin-checklinks"
  [plugins.inputs]
  entryPoints = [
    "sitemap-index.xml",
  ]
  skipPatterns = [
    "404*"
  ]
  todoPatterns = [
    "feed*"
  ]

[[plugins]]
package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "lighthouse/index.html"

  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    pwa = 0.0 # Skip PWA threshold for now
